### ISSUE TITLE
Cannot install via pip

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#137] opened 2015-06-04 03:18 UTC
_From [gertbur...@gmail.com](https://code.google.com/u/112018209892827490839/) on July 09, 2013 07:04:10_

What steps will reproduce the problem? 
1. pip install dpkt
2. Fails with error "DistributionNotFound: No distributions at all found for dpkt" 
3. My guess is there is no download_url set for dpkt on pypi. See http://docs.python.org/2/distutils/setupscript.html#additional-meta-data for more info.

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=111_

**Comment by sunhao2014** [comment] 2015-06-09 07:26
Actually I couldn't reproduce this problem. I tried the "pip install dpkt" command on both Win and Ubuntu platform, however it works well on my computer. Please see the snapshot on the aforementioned platform.
![image](https://cloud.githubusercontent.com/assets/5916357/8052588/56d9f254-0ebb-11e5-9f42-390d17e7c2aa.png)
![image](https://cloud.githubusercontent.com/assets/5916357/8052594/6df500d2-0ebb-11e5-922c-7aa7fad76fe3.png)

Since this is an issue submitted in 2013, I guess there might be some configuration problems at that time. Nonetheless it seems to have been fixed now.

**Comment by kbandla** [comment] 2015-06-09 15:48
:+1: this issue can be closed

**Closed** 2015-06-10 01:18 UTC
Labels: bug, imported
