### ISSUE TITLE
Setting .text for a DNS TXT object throws exception in Python3

### ISSUE THREAD

**Issue by jjo-sec** [kbandla/dpkt#375] opened 2017-06-18 20:17 UTC
>   File "/usr/local/lib/python3.5/dist-packages/dpkt/dns.py", line 375, in __len__
>     return len(str(self))
>   File "/usr/local/lib/python3.5/dist-packages/dpkt/dpkt.py", line 141, in __str__
>     return str(self.__bytes__())
>   File "/usr/local/lib/python3.5/dist-packages/dpkt/dns.py", line 386, in __bytes__
>     buf = self.pack_rr(buf, rr)
>   File "/usr/local/lib/python3.5/dist-packages/dpkt/dns.py", line 342, in pack_rr
>     rdata = rr.pack_rdata(len(buf) + len(name) + 10, self.label_ptrs)
>   File "/usr/local/lib/python3.5/dist-packages/dpkt/dns.py", line 280, in pack_rdata
>     for x in self.text])
> TypeError: sequence item 0: expected a bytes-like object, str found

Using a byte array instead of a python3 string when setting .text generates a different exception

> TypeError: object of type 'int' has no len()

Was not able to determine a proper fix for the issue that makes both python2 and 3 happy without needing to check the version_info to perform the operation in a different manner depending on python version

**Comment by brifordwylie** [comment] 2017-06-19 14:20
Thanks @arbor-jjones we'll try to peek at this soon... can you put a small script that reproduces the error into this Issue?

**Comment by crocogorical** [comment] 2017-11-11 18:30
This will raise a `TypeError: object of type 'int' has no len()`
```python3
DNS.RR(type=DNS_TXT, text=b'Noonien Soong').pack_rdata(0, {})
```

This will raise a `TypeError: sequence item 0: expected a bytes-like object, str found`
```python3
DNS.RR(type=DNS_TXT, text='Noonien Soong').pack_rdata(0, {})
```

**Comment by obormot** [comment] 2018-12-04 06:30
Looks like this was addressed, closing. `.text` needs to be a list:
```
def test_rdata_TXT():
    rr = DNS.RR(
        type=DNS_TXT,
        text=[b'v=spf1 ptr ?all', b'a=something']
    )
    packdata = rr.pack_rdata(0, {})
    correct = b'\x0fv=spf1 ptr ?all\x0ba=something'
    assert packdata == correct
```
Test by the OP works as well, when changed to a list:
```
>>> DNS.RR(type=dpkt.dns.DNS_TXT, text=[b'Noonien Soong']).pack_rdata(0, {})
b'\rNoonien Soong'
```

**Closed by obormot** 2018-12-04 06:30 UTC
Labels: bug, python 3
