### ISSUE TITLE
Python3 OSPF default auth field packet packing error

### ISSUE THREAD

**Issue by nfz1** [kbandla/dpkt#385] opened 2017-08-31 04:41 UTC
There is a bug in the current version of dpkt on Python3. If the auth header field is omitted when initiating an OSPF packet, an exception is raised. Here is a quick test and stack-trace using the Python3 interpreter.

```Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dpkt.ospf import OSPF
>>> packet = OSPF(v=1,type=1,area=0,len=0,router=0,data=b'')
>>> packet.__bytes__()
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/dpkt/dpkt.py", line 150, in pack_hdr
    *[getattr(self, k) for k in self.__hdr_fields__])
struct.error: argument for 's' must be a bytes object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/dpkt/dpkt.py", line 160, in pack_hdr
    return struct.pack(self.__hdr_fmt__, *vals)
struct.error: argument for 's' must be a bytes object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/dpkt/ospf.py", line 36, in __bytes__
    self.sum = dpkt.in_cksum(dpkt.Packet.__bytes__(self))
  File "/usr/local/lib/python3.5/dist-packages/dpkt/dpkt.py", line 144, in __bytes__
    return self.pack_hdr() + bytes(self.data)
  File "/usr/local/lib/python3.5/dist-packages/dpkt/dpkt.py", line 162, in pack_hdr
    raise PackError(str(e))
dpkt.dpkt.PackError: argument for 's' must be a bytes object
```

The problem is due to the auth field having an invalid value set as its default `''`. This should be `b''` in python 3 as strings are now stored in Unicode. Can also fix this by using the encode method to translate the string to bytes before the packet processing occurs, but this may be more messy.

Here is a link to the file and line in question. [dpkt/ospf.py line 31](https://github.com/kbandla/dpkt/blob/master/dpkt/ospf.py#L31)

If we set the auth field value to `b''` we get the expected output.

```Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dpkt.ospf import OSPF
>>> packet = OSPF(v=1,type=1,area=0,len=0,router=0,auth=b'',data=b'')
>>> packet.__bytes__()
b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfe\xfe\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

**Comment by obormot** [comment] 2019-10-25 18:41
This should be now resolved in master branch, by merging https://github.com/kbandla/dpkt/pull/461 
Please reopen if the issue if the problem is still occurring

**Closed by obormot** 2019-10-25 18:41 UTC
